#include <pebble.h>

#ifndef PBL_PLATFORM_BASALT  
  
#define NO_OF_FRAMES 25  

// images used for Aplite sequence animation
const int fire_aplite_res[] = {  

RESOURCE_ID_BW_FIRE_FRAME_1,
RESOURCE_ID_BW_FIRE_FRAME_2,
RESOURCE_ID_BW_FIRE_FRAME_3,
RESOURCE_ID_BW_FIRE_FRAME_4,
RESOURCE_ID_BW_FIRE_FRAME_5,
RESOURCE_ID_BW_FIRE_FRAME_6,
RESOURCE_ID_BW_FIRE_FRAME_7,
RESOURCE_ID_BW_FIRE_FRAME_8,
RESOURCE_ID_BW_FIRE_FRAME_9,
RESOURCE_ID_BW_FIRE_FRAME_10,
RESOURCE_ID_BW_FIRE_FRAME_11,
RESOURCE_ID_BW_FIRE_FRAME_12,
RESOURCE_ID_BW_FIRE_FRAME_13,
RESOURCE_ID_BW_FIRE_FRAME_14,
RESOURCE_ID_BW_FIRE_FRAME_15,
RESOURCE_ID_BW_FIRE_FRAME_16,
RESOURCE_ID_BW_FIRE_FRAME_17,
RESOURCE_ID_BW_FIRE_FRAME_18,
RESOURCE_ID_BW_FIRE_FRAME_19,
RESOURCE_ID_BW_FIRE_FRAME_20,
RESOURCE_ID_BW_FIRE_FRAME_21,
RESOURCE_ID_BW_FIRE_FRAME_22,
RESOURCE_ID_BW_FIRE_FRAME_23,
RESOURCE_ID_BW_FIRE_FRAME_24,
RESOURCE_ID_BW_FIRE_FRAME_25

};

#endif